### ISSUE TITLE
'Sofa\Eloquence\ServiceProvider' not found...

### ISSUE THREAD

**Issue by Giregar** [jarektkaczyk/eloquence#58]
Hello,
I'm following the installation manual, but get an "'Sofa\Eloquence\ServiceProvider' not found" error.
I added "sofa/eloquence": "~5.1@dev" to my composer.json and "Sofa\Eloquence\ServiceProvider::class," to my config/app.php.
And run "php composer.phar update".

What could be the problem?

_[RuntimeException]                                                                       
  Error Output: PHP Fatal error:  Class 'Sofa\Eloquence\ServiceProvider' not found in /.../vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146_

**Comment by jarektkaczyk** [comment]
The class is there for sure. Run `artisan clear-compiled && composer dump-autoload` and check again.

Otherwise delete the vendor folder and run `composer install` again.

**Comment by spagu** [comment]
Did as you suggested. Does not help.

**Comment by ngrcode** [comment]
I had the same problem and solving that took one day finaly I searched in github the procedure of installation and I changed Sofa\Eloquence\ServiceProvider::class to Sofa\Eloquence\BaseServiceProvider::class
and It worked correctly.

**Comment by jarektkaczyk** [comment]
@michaellindahl thanks for comment. I believe `composer dump-autoload -o` should resolve the problem as well.

Anyway, as you pointed out, this is clearly invalid behavior of the framework.

**Comment by michaellindahl** [comment]
Oddly enough that didn't fix it either.

So it looks like `ComposerScripts::postAutoloadDump` is called when you `dump-autoload`. That calls `clearCompiled` which is intended to "Clear the cached Laravel bootstrapping files." but that only clears `services.php` and `packages.php` and not `config.php`
